{
  "openapi": "3.0.0",
  "info": {
    "description": "User Management Flask API",
    "termsOfService": "/tos",
    "title": "A Flask REST API for User data",
    "version": "0.0.1"
  },
  "paths": {
    "/users/": {
      "get": {
        "responses": {
          "200": {
            "description": "Successfully returned all users",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": [{
                      "age": 100,
                      "firstName": "first",
                      "lastName": "last"
                    }]
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/UsersList"
                }
              }
            }
          }
        },
        "summary": "Returns a list of all users"
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User",
                "type": "string"
              }
            }
          },
          "description": "the user to create",
          "required": true
        },
        "responses": {
          "201": {
            "description": "User was successfully created",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "age": 100,
                      "firstName": "first",
                      "lastName": "last"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        },
        "summary": "Creates a user"
      }
    },
    "/users/{user_id}/": {
      "get": {
        "parameters": [
          {
            "description": "the id of the user",
            "in": "path",
            "name": "user_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A user",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "age": 100,
                      "firstName": "Adam",
                      "lastName": "test"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "description": "No user exists"
          }
        },
        "summary": "Returns a user if one exists"
      }
    }
  },
  "components": {
    "schemas": {
      "UsersList": {
          "type": "array",
          "items": {
              "$ref": "#/components/schemas/User"
          }
      },
      "User": {
        "properties": {
          "age": {
            "type": "number"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          }
        },
        "type": "object"
      }
    }
  }
}